version: "3.8"

services:

  keycloak:
    image: docker.io/bitnami/keycloak:20
    container_name: aulas_keycloak
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: password
      KEYCLOAK_DATABASE_VENDOR: POSTGRES
      KEYCLOAK_DATABASE_HOST: host.docker.internal
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: bilinguismo_db_user
      KEYCLOAK_DATABASE_PASSWORD: Bilinguismo2022*
      KEYCLOAK_DATABASE_SCHEMA: public
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_BIND_ADDRESS: 0.0.0.0
      KEYCLOAK_ENABLE_STATISTICS: true
      KEYCLOAK_PRODUCTION: false
      KC_HTTP_RELATIVE_PATH: "/auth"
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
      KEYCLOAK_LOG_LEVEL: INFO
      THEME_NAME: aulassteam
    ports:
      - 8080:8080
      # - 8443:8443
    volumes:
      - ./keycloak/config:/opt/bitnami/keycloak/data/import
      - ./keycloak/theme:/opt/bitnami/keycloak/providers
    networks:
      - aulas-steam-net

  backend:
    image: bilinguismotalentum/backend:quindio-1.0.0
    container_name: aulas_steam_reporter_backend
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JWKS_URI: http://aulasquindio.local/auth/realms/aulassteamquindio/protocol/openid-connect/certs
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: "%Aqrme3020"
      DB_DATABASE: simat_db
      KEYCLOAK_DB_HOST: host.docker.internal
      KEYCLOAK_DB_PORT: 5432
      KEYCLOAK_DB_USER: keycloak
      KEYCLOAK_DB_PASSWORD: "%Aqrme3020"
      KEYCLOAK_DB_NAME: keycloak
      KEYCLOAK_API_URL: /admin/realms/aulassteamquindio
      KEYCLOAK_BASE_URL: http://aulasquindio.local/auth
      KEYCLOAK_CLIENT_ID: client-api
      KEYCLOAK_CLIENT_SECRET: ZwwyVH63X1HfSOsvcLSNxoK4xLjuwHYg
      KEYCLOAK_GET_TOKEN_URL: /realms/aulassteamvalle/protocol/openid-connect/token
    ports:
      - "4000:4000"
    depends_on:
      - keycloak
    networks:
      - aulas-steam-net

  frontend:
    image: bilinguismotalentum/frontend:quindio-1.0.0
    container_name: aulas_steam_reporter_frontend
    restart: always
    environment:
      KEYCLOAK_CLIENT_ID: si-frontend
      KEYCLOAK_CLIENT_SECRET: 616a597f-2af2-409d-bbd6-f5a0787d90d7
      KEYCLOAK_HOST: http://aulasquindio.local/auth
      KEYCLOAK_REALM: aulassteamquindio
      NEXT_PUBLIC_DEFAULT_AUTH_PROVIDER: keycloak
      NEXT_PUBLIC_BACKEND: http://aulasquindio.local/api
      NEXTAUTH_URL: http://aulasquindio.local/si
      NEXT_PUBLIC_DATABASE_KEY_NAME: bilinguismo_db

    ports: 
      - "3000:3000"
    depends_on:
      - backend
      - keycloak
    networks:
      - aulas-steam-net

  moodle:
    image: docker.io/bitnami/moodle:4
    container_name: aulas_quindio_moodle
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: host.docker.internal
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_USER: root
      MOODLE_DATABASE_PASSWORD: "%Aqrme3020"
      MOODLE_DATABASE_NAME: moodledb
      MOODLE_SKIP_BOOTSTRAP: true
    ports:
      - '5000:8080'
    networks:
      - aulas-steam-net
    volumes:
      - '/apps/moodle/moodledata:/bitnami/moodledata'
      - '/apps/moodle/moodle:/bitnami/moodle'
    
networks:
  aulas-steam-net:
    driver: bridge
